milahaina: Drop performancemode and workloadclassifier ** needs frameworks support
crash log

07-29 20:19:19.517  9330  9330 D AndroidRuntime: Shutting down VM
07-29 20:19:19.518  9330  9330 E AndroidRuntime: FATAL EXCEPTION: main
07-29 20:19:19.518  9330  9330 E AndroidRuntime: Process: com.qualcomm.qti.performancemode, PID: 9330
07-29 20:19:19.518  9330  9330 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/util/BoostFramework;
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at com.qualcomm.qti.performancemode.api.PerformanceModeManager.<init>(PerformanceModeManager.java:29)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at com.qualcomm.qti.performancemode.api.PerformanceModeManager.<clinit>(PerformanceModeManager.java:14)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at com.qualcomm.qti.performancemode.api.PerformanceModeManager.getInstance(PerformanceModeManager.java:25)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at com.qualcomm.qti.performancemode.SystemEventReceiver.onReceive(SystemEventReceiver.java:33)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-29 20:19:19.518  9330  9330 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.util.BoostFramework
07-29 20:19:19.518  9330  9330 E AndroidRuntime: 	... 14 more

07-29 20:19:19.534  6217  6217 D AndroidRuntime: Shutting down VM
07-29 20:19:19.535  6217  6217 E AndroidRuntime: FATAL EXCEPTION: main
07-29 20:19:19.535  6217  6217 E AndroidRuntime: Process: com.qualcomm.qti.workloadclassifier, PID: 6217
07-29 20:19:19.535  6217  6217 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.qualcomm.qti.Performance.native_perf_get_prop(java.lang.String, java.lang.String) (tried Java_com_qualcomm_qti_Performance_native_1perf_1get_1prop and Java_com_qualcomm_qti_Performance_native_1perf_1get_1prop__Ljava_lang_String_2Ljava_lang_String_2)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at com.qualcomm.qti.Performance.native_perf_get_prop(Native Method)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at com.qualcomm.qti.Performance.perfGetProp(Performance.java:493)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at com.qualcomm.qti.workloadclassifier.WLCReceiver.onReceive(WLCReceiver.java:25)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-29 20:19:19.535  6217  6217 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)